[package]
name = "xtask"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[package.metadata.xtk_test.evidences]
TEST_EVIDENCES_OUTPUT_PATH = ".artifacts/e2e"

[[bin]]
name = "xtask"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
cargo_metadata = { workspace = true }
clap = { workspace = true }
clap-cargo = { workspace = true }
percent-encoding = { workspace = true }
process-wrap = { workspace = true }
tempfile = { workspace = true }
xtk_test = { workspace = true }

[lints]
workspace = true
