[package]
description = "Operation contracts and generated gRPC bindings for pwf"
name = "pwf-wire"
version.workspace = true
rust-version.workspace = true
repository.workspace = true
readme.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
name = "pwf_wire"
path = "src/lib.rs"

[dependencies]
prost = { workspace = true }
serde = { workspace = true }
pwf-models = { workspace = true }
thiserror = { workspace = true }
tonic = { workspace = true }
tonic-prost = { workspace = true }

[lints]
workspace = true
