[package]
description = "Validated task and project values for pwf"
name = "pwf-models"
version.workspace = true
rust-version.workspace = true
repository.workspace = true
readme.workspace = true
edition.workspace = true
license.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
name = "pwf_models"
path = "src/lib.rs"

[dependencies]
jiff = { workspace = true }
nutype = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
