[profile.default]
status-level = "fail"
final-status-level = "fail"
failure-output = "immediate"
success-output = "never"

[profile.process]
inherits = "default"
fail-fast = false
global-timeout = "1h"
