[package]
name = "pwf-application"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
prompt-lanes = { workspace = true }
pwf-domain = { workspace = true }
cqrsy = { workspace = true }
regex = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }

[lints]
workspace = true
