[package]
name = "pwf-migrator"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[[bin]]
name = "pwf-migrator"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
directories = { workspace = true }
pwf-application = { workspace = true }
pwf-infra = { workspace = true }
pwf-models = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }

[lints]
workspace = true
