[package]
description = "Embedded SQLite migrations for pwf"
name = "pwf-migrator"
version.workspace = true
rust-version.workspace = true
repository.workspace = true
readme.workspace = true
edition.workspace = true
license.workspace = true
license-file.workspace = true
publish.workspace = true

[dependencies]
anyhow = { workspace = true }
pwf-infra = { workspace = true }

[dev-dependencies]
sqlx = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }

[lints]
workspace = true
